# Generated by Django 3.1 on 2020-08-26 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=50)),
                ('ename', models.TextField(default='Mr.')),
                ('eemail', models.CharField(max_length=50)),
                ('eaddress', models.TextField(max_length=50)),
                ('econtact', models.CharField(max_length=50)),
                ('edesign', models.CharField(max_length=50)),
                ('ecursal', models.CharField(max_length=50)),
                ('edoj', models.CharField(max_length=50)),
                ('ewexp', models.CharField(max_length=50)),
                ('epcomp', models.CharField(max_length=50)),
                ('edpt', models.CharField(max_length=50)),
                ('epp', models.CharField(max_length=50)),
                ('set_name', models.CharField(max_length=50)),
            ],
        ),
    ]
