# Generated by Django 3.1 on 2020-08-26 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='set_name',
        ),
    ]
