# Generated by Django 3.1 on 2020-08-26 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_set_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='epp',
        ),
        migrations.AddField(
            model_name='employee',
            name='picname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='employee',
            name='picurl',
            field=models.TextField(default='-'),
        ),
    ]
