# Generated by Django 3.1 on 2020-08-26 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200826_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='picname',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='picurl',
        ),
    ]
