# Generated by Django 3.1 on 2020-08-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20200826_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='eba',
            field=models.CharField(default='', max_length=50),
        ),
    ]
